config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, controllers: { registrations: "users/registrations" }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # get 'home/index'
  # get 'tools/index'
  # get 'tools/show'
  # get 'producer_companies/index'
  # get 'producer_companies/show'
  resources :pages, except: [:show]
  get "pages/:permalink" => "pages#permalink", as: "permalink" # using in ruby is : permalink_path

  root to: "home#index"
  resources :tools, only: %i[index show] do
    collection do
      get "search"
    end
  end
  resources :producer_companies, only: %i[index show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :cart, only: %i[create destroy]

  # devise_for :accounts, controllers: { registrations: "accounts/registrations" }
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
  validates :title, :content, :permalink, presence: true
  validates :permalink, uniqueness: true
end

app/models/producer_company.rb
class ProducerCompany < ApplicationRecord
  has_many :tools
  validates :name, presence: true, uniqueness: true

  def self.ordered_by_tools
    self.select("producer_companies.*")
        .select("COUNT(producer_companies.id) as tool_count")
        .left_joins(:tools)
        .group("producer_companies.id")
        .order("tool_count DESC")
  end
end

app/models/tool.rb
class Tool < ApplicationRecord
  has_one_attached :image
  belongs_to :producer_company
  has_many :tool_types
  has_many :tools, through: :tool_types

  validates :name, :description, :price, :quantity, presence: true
  validates :name, uniqueness: true
  validates :price, :quantity, numericality: true
end

app/models/tool_type.rb
class ToolType < ApplicationRecord
  belongs_to :tool
  belongs_to :type
end

app/models/type.rb
class Type < ApplicationRecord
  has_many :tool_types
  has_many :tools, through: :tool_types
  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # resources :users, only: %i[show edit update]
  belongs_to :province
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :initialize_session, :load_categories # current_customer
  helper_method :cart

  helper_method :cms_pages

  def cms_pages
    Page.all
  end

  private

  def initialize_session
    session[:shopping_cart] ||= []
  end

  def cart
    Tool.find(session[:shopping_cart])
  end

  def load_categories
    @c = ProducerCompany.all.map { |u| [u.name, u.id] }
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  # POST /cart
  def create
    # product_id = params[:id]
    # logger.debug("Adding #{product_id} to cart.")
    # tool = Tool.find(product_id)
    # session[:shopping_cart] >> product_id
    # redirect_to root_path

    logger.debug("Adding #{params[:id]} to cart.")
    id = params[:id].to_i
    session[:shopping_cart] << id

    tool = Tool.find(id)
    flash[:notice] = "#{tool.name} was succesfully added to cart! Cheers 🍻"

    redirect_to tools_path
  end

  # DELETE /cart/:id
  def destroy
    # removes params[:id]
    logger.debug("Removing #{params[:id]} to cart.")
    id = params[:id].to_i
    session[:shopping_cart].delete(id)
    tool = Tool.find(id)
    flash[:notice] = " #{tool.name} removed from cart."
    redirect_to tools_path
  end
end

# 7 resful routs   index new create show edit update destroy

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @tools = Tool.includes(:producer_company)
                 .order("price DESC")
                 .limit(3)
    @producer_companies = ProducerCompany.ordered_by_tools.limit(3)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: %i[edit update destroy]
  http_basic_authenticate_with name: "admin", password: "secret", except: [:permalink]

  # GET /pages or /pages.json
  def index
    @pages = Page.all
  end

  # GET /pages/1 or /pages/1.json
  def permalink
    @page = Page.find_by(permalink: params[:permalink])
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit; end

  # POST /pages or /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html do
          redirect_to permalink_path(@page.permalink), notice: "Page was successfully created."
        end
        format.json { render :show, status: :created, location: permalink_path(@page.permalink) }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1 or /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html do
          redirect_to permalink_path(@page.permalink), notice: "Page was successfully updated."
        end
        format.json { render :show, status: :ok, location: permalink_path(@page.permalink) }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1 or /pages/1.json
  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to pages_url, notice: "Page was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_page
    @page = Page.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def page_params
    params.require(:page).permit(:title, :content, :permalink)
  end
end

app/controllers/producer_companies_controller.rb
class ProducerCompaniesController < ApplicationController
  def index
    @producer_companies = ProducerCompany.ordered_by_tools
  end

  def show
    @producer_company = ProducerCompany.find(params[:id])
  end
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  def index
    # @tools = Tool.includes(:producer_company).all
    @users = User.all

    @tools  = Tool.page(params[:page])
    # @tools  = Tool.paginate(page: params[:page], per_page: 2)  first gem
  end

  def show
    @tool = Tool.find(params[:id])
  end

  # def search
  #   wildcard_search = "%#{params[:keywords]}%"
  #   @tools = Tool.where("name LIKE ?", wildcard_search)
  # end

  def search
    # @tools = if !params[:id].empty?
    #            Tool.joins(:tool_types).where(tool_types: { id: params[:id] }).where(
    #              "name OR description LIKE ?", "%#{params[:search_term]}%"
    #            )
    @tools = if !params[:id].empty?
               Tool.where("producer_company_id = #{params[:id]}").where(
                 "name OR description LIKE ?", "%#{params[:search_term]}%"
               )

             else
               #   wildcard_search = "%#{params[:keywords]}%"
               # @tools = Tool.where("name LIKE ?", wildcard_search)
               Tool.where("name OR description LIKE ?", "%#{params[:search_term]}%")
             end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/producer_companies_helper.rb
module ProducerCompaniesHelper
end

app/helpers/tools_helper.rb
module ToolsHelper
end

app/views/common/_footer.html.erb
<hr>
<footer>
  <p><em>The Scott Depot</em></p>
  <ul class="mt-5">
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "Tools", tools_path %></li>
    <li><%= link_to "Brands", producer_companies_path %></li>

    <% cms_pages.each do |page| %>
      <li><%= link_to page.title, permalink_path(page.permalink) %> </li>

    <% end %>



  </ul>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">The Scott Depot</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">

      <% if user_signed_in? %>
        <li class="nav-item">
           <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>

        <li class="nav-item">
           <%= link_to 'Edit', edit_user_registration_path, class: 'nav-link' %>
        </li>
      <% else %>

        <li class="nav-item">
          <%= link_to 'Register', new_user_registration_path, class: 'nav-link' %>
        </li>
         <li class="nav-item">
           <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
        </li>

      <% end %>

      </ul>
    </div>
  </div>
</nav>

app/views/common/_scotts_fav.html.erb
<hr>
<footer>
  <p><em>The Scott Depot</em></p>
  <ul class="mt-5">

<li><%= text = " Get your discount code for %100 of your first order! https://www.youtube.com/watch?v=dQw4w9WgXcQ"
html_text = text.gsub(URI.regexp, '<a href="\0">\0</a>').html_safe %></li>

<% cms_pages.each do |page| %>
      <li><%= link_to page.title, permalink_path(page.permalink) %> </li>
<% end %>

<%# <li><= link_to "About My Data", permalink_path('about_the_data') ></li>
<li><= link_to "Contact", permalink_path('contact') ></li> %>

  </ul>
</footer>

app/views/home/index.html.erb
<% name = current_user.present? ? current_user.email : 'What are you waiting for, get registerd or sign in so you can shop!' %>


<h1> Welcome, <%= name%> </h1>

<div class="columns is-half">
  <div class="column">
    <h2 class="title is-2"> Best Selling Tools </h2>
    <ol class="ml-5">
      <% @tools.each do | tool | %>
              <div class="card margin-bottom mb-6 margin-right mb-6">
                <div class="card-content">
                    <li>
                      <%= link_to tool.name, tool %>
                      <em>(<%= tool.producer_company.name %>) </em>
                    </li>
                  </div>
              </div>
      <% end %>
    </ol>
  </div>

  <div class="column is-half">
     <h2 class="title is-2"> Top 3 Brands </h2>
     <ol class="ml-5">
              <%# <div class="card margin-bottom mb-6 margin-right mb-6">
                <div class="card-content"> %>
                    <%= render @producer_companies %>
                  <%# </div>
              </div> %>
    </ol>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:html_title) + " - " if content_for?(:html_title)%> Scotts Depot </title>   <%# Use this for Breadcrumbs! %>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%# Bootstrap %>
    <link rel="stylesheet" href=" https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">

    <%# BULMA %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('favicon.ico') %>


  </head>

  <body>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= render 'common/navbar' %>

    <section class="section box">
      <section class="section">


      <%# Popup flash notice %>
      <% if flash[:notice] %>
         <p><%= flash[:notice] %></p>
      <% end%>

      <div class="buttons box has-background-warning-light">
        <div class="containter">
          <h1 class="button is-dark"><%= link_to 'Home', root_path %></h1>
          <h1 class="button is-dark"><%= link_to "Shop", tools_path %></h1>
          <h1 class="button is-dark"><%= link_to "Brands", producer_companies_path %></h1>


        <%= form_with(url: search_tools_path, local: true, method: "get", class: 'd-flex') do %>
          <div class="field is-grouped mb-5">
            <div class="control is-expanded">
              <%= text_field_tag(:search_term, nil, class: 'form-control', placeholder: 'Search Tool By Name') %>
              <%= select_tag(:id, options_for_select(@c),{ :include_blank => "select category"}) %>
            </div>
            <div class="control">
              <%= submit_tag("Search", class: "btn btn-warning") %>
            </div>
          </div>
        <% end %>


        </div>

        <%# shopping cart %>
      <nav class="level-right">
        <%= link_to image_tag("shopping-cart.png", width:60), root_path %>
          <ul>
            <li>
              Cart
              <% if cart.present? %>
                <sup> <%= cart.size %><sup>
                  <ul>
                    <% cart.each do |tool| %>
                      <li>
                        <%= tool.name %> <%= link_to '➖', cart_path(tool), method: :delete %>
                      </li>
                    <%end%>
                  </ul>
              <%end%>
            </li>
          </ul>
      </nav>

      </div>

      <%= yield %>

      <% if controller_name == 'home' %>
        <%= render partial: 'common/scotts_fav'%>
      <% else %>
        <%= render partial: 'common/footer' %>
      <% end %>

      </section>

    </section>
  </body>
</html>

app/views/pages/_form.html.erb
<%= form_with(model: page) do |form| %>
  <% if page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
        <% page.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title, class: "label"%>
    <%= form.text_field :title, class: "input"  %>
  </div>

  <div class="field">
    <%= form.label :content, class: "label"%>
    <%= form.text_area :content, class: "textarea"  %>
  </div>

  <div class="field">
    <%= form.label :permalink, class: "label" %>
    <%= form.text_field :permalink , class: "input"  %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h2 class="title is-4">Editing Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<p id="notice"><%= notice %></p>

<h2 class="title is-4">Pages</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Permalink</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= page.title %></td>
        <td><%= truncate page.content %></td>
        <td><%= page.permalink %></td>

        <td><%= link_to 'Show', page, class: 'button is-warning' %> </td>
        <td><%= link_to 'Edit', edit_page_path(page), class: 'button is-info' %></td>
        <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' }, class: 'button is-danger' %></td>
        <br>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Page', new_page_path, class: 'button is-danger'%>

app/views/pages/new.html.erb
<h2 class="title is-4">New Page</h1>


<%= render 'form', page: @page %>

<%= link_to 'Back', pages_path %>

app/views/pages/permalink.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @page.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @page.content %>
</p>

<p>
  <strong>Permalink:</strong>
  <%= @page.permalink %>
</p>

<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @page.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @page.content %>
</p>

<p>
  <strong>Permalink:</strong>
  <%= @page.permalink %>
</p>

<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>

app/views/producer_companies/_producer_company.html.erb
    <div class="card margin-bottom mb-6 margin-right mb-6">
        <div class="card-content">
          <li>
          <%= link_to producer_company.name, producer_company %>
          <em>(<%= pluralize producer_company.tool_count, "Product" %> EDIT IN _producer_company partial) </em>
          </li>

      </div>
    </div>

app/views/producer_companies/index.html.erb
 <h2 class="title is-2"> Our Brands </h2>
     <ol class="ml-5">
      <%= render @producer_companies %>
    </ol>

app/views/producer_companies/show.html.erb
<h2 class="title is-2"> <%= @producer_company.name %> </h2>

<p class='mb-5 box'>
  <%= @producer_company.name%> Makes <%= @producer_company.tools.count %> different Tools.
</p>

<h3 class='title is-3 box'> Tools made by <%= @producer_company.name%></h3>


<ul>
  <%# we can also use render partial for producer_company here for a different look %>
    <% @producer_company.tools.each do |tool|%>
      <div class="card margin-bottom mb-6 margin-right mb-6">
        <div class="card-content">

            <li> There are <%= tool.quantity %>, <%= link_to tool.name, tool %>'s Available </li>

            <%# (<= pluralize publisher_company.game_count, "Best Game"> Best Games   find in views>home>index) %>
       </div>
      </div>
    <% end %>

  </ul>

app/views/tools/_tool.html.erb
<div class="container is-max-desktop">
    <div class="notification white-ter	">
        <div class="tile is-parent">
            <article class="tile is-child notification has-background-grey-light">
                <h2 class="title is-2">
                  <% if show_link %>
                    <%= link_to tool.name, tool %>
                  <% else %>
                      <%= tool.name %>
                  <% end %>
                </h2>
            <article class="message is-dark">
                <div class="message-header has-background-warning-dark">
                <p>Tool Description</p>
                </div>
                  <div class="message-body">
                  <%= tool.description%>
                  </div>
            </article>

            <p> <strong>Quantity Remaining:</strong> <%= tool.quantity %> <strong>/150</strong> </p>
            <progress class="progress " value="<%= tool.quantity %>" max=150>


              <p> Quantity Remaining </p>
               <%= tool.quantity %>
            </progress>


            <% if tool.image.present? %>
            <%# <p>IMAGE!!</p> %>
              <p><%= image_tag tool.image.variant(resize_to_limit: [285, 285]).processed %></p>
            <% end %>

    <p>
      <strong> Quantity: </strong>
      <%= tool.quantity %>
    </p>

    <p>
      <strong> Price: $</strong>
      <%= number_to_currency tool.price %>
    </p>

    <p>
      <strong> Brand: </strong>
      <%= link_to tool.producer_company.name, tool.producer_company %>
    </p>

     <%# Pass the id of the product to the cart %>
    <% if cart.include?(tool) %>
      <%= button_to cart_path(tool), method: :delete do %>
        Remove From Cart 😪
    <% end %>
    <% else %>
      <%= form_with url: cart_index_path, method: :post do %>
        <%= hidden_field_tag(:id, tool.id) %>
        <%= button_tag 'Add to Cart' %>
      <% end %>
    <% end %>



      </div>
      <figure class="media-left">
        <p class="image is-64x64">
          <img src="https://www.pikpng.com/pngl/m/150-1501872_100-money-back-guarantee-circle-clipart.png">
        </p>
      </figure>
  <div class="media-content">
    <div class="content">
      <p>
        <strong>The Famouse 100 Year Garuntee!</strong> <small>Scott 100</small>
        <br>
        This product comes with Scotts 100 year garuntee or your money back!
      </p>
      </article>
      </div>
    </div>
</div>


          <%# <p class="title">Middle tile</p>
          <p class="subtitle">With an image</p>
          <figure class="image is-4by3">
            <img src="https://bulma.io/images/placeholders/640x480.png">
          </figure> %>

app/views/tools/index.html.erb
<h2 class="title is-2"> Buy Some Tools! </h2>

<%# <%= render @tools %>
<%# <%= will_paginate @tools %>

<%= @users.each do |user| %>
<li><%= user.province.name %> </li>
<%end%>

 <% @tools.each do |tool| %>
    <li><%= link_to tool.name, tool %></li>
    <% end %>


<%= paginate @tools %>
<%= render partial: @tools, locals: {show_link: true} %>

app/views/tools/search.html.erb
<p class="mb-5">
  Found <%= pluralize(@tools.count, 'name') %> when searching for: <%= params[:search_term] %>
</p>

<ul>
  <% @tools.each do |tool| %>
    <li><%= link_to tool.name, tool %></li>
    <% end %>
</ul>

app/views/tools/show.html.erb
<%# <h1>Tools#show</h1>
<p>Find me in app/views/tools/show.html.erb</p> %>
<% content_for(:html_title) { @tool.name} %>

<%# <%= render @tool %>
<%= render partial: @tool, locals: {show_link: false} %>